# Generated by Django 6.0.7 on 2026-07-11 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dept', models.CharField(max_length=50)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('verdict', models.CharField(blank=True, default='', max_length=50)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('matched_all', models.JSONField(blank=True, default=list)),
                ('gaps', models.JSONField(blank=True, default=list)),
                ('years', models.FloatField(default=0)),
                ('edu', models.CharField(blank=True, default='', max_length=100)),
                ('position', models.CharField(blank=True, default='', max_length=150)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('source', models.CharField(blank=True, default='Other', max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('stage', models.CharField(choices=[('New', 'New'), ('Shortlisted', 'Shortlisted'), ('Interview', 'Interview'), ('Selected', 'Selected'), ('Rejected', 'Rejected')], default='New', max_length=20)),
                ('stage_at', models.DateTimeField(blank=True, null=True)),
                ('selected_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
    ]
